type dayArrtype = [string | undefined, number, string];

export const DefaultAdminData = (dayArr: dayArrtype[]) => {
  return [
    {
      dailyMenuId: null,
      menuDate: dayArr[0][2],
      holidayFg: 'N',
      restaurantOpenFg: 'Y',
      menuDetailsList: [
        {
          menuDetailsId: null,
          dailyMenuId: null,
          dailyMenuDate: null,
          dailyMenuCategory: null,
          mainMealYn: 'Y',
          menuDetailsName: '한식',
          menuDetailsImgUrl: null,
          subBridgeList: [
            {
              bridgeId: null,
              menuDetailsId: null,
              menuItemId: null,
              menuItemName: ' ',
              mainMenuYn: 'Y',
              submenuDetails: null,
              submenuItem: null,
            },
            {
              bridgeId: null,
              menuDetailsId: null,
              menuItemId: null,
              menuItemName: ' ',
              mainMenuYn: 'N',
              submenuDetails: null,
              submenuItem: null,
            },
            {
              bridgeId: null,
              menuDetailsId: null,
              menuItemId: null,
              menuItemName: ' ',
              mainMenuYn: 'N',
              submenuDetails: null,
              submenuItem: null,
            },
            {
              bridgeId: null,
              menuDetailsId: null,
              menuItemId: null,
              menuItemName: ' ',
              mainMenuYn: 'N',
              submenuDetails: null,
              submenuItem: null,
            },
            {
              bridgeId: null,
              menuDetailsId: null,
              menuItemId: null,
              menuItemName: ' ',
              mainMenuYn: 'N',
              submenuDetails: null,
              submenuItem: null,
            },
            {
              bridgeId: null,
              menuDetailsId: null,
              menuItemId: null,
              menuItemName: ' ',
              mainMenuYn: 'N',
              submenuDetails: null,
              submenuItem: null,
            },
          ],
        },
        {
          menuDetailsId: null,
          dailyMenuId: null,
          dailyMenuDate: null,
          dailyMenuCategory: null,
          mainMealYn: 'Y',
          menuDetailsName: '일품',
          menuDetailsImgUrl: null,
          subBridgeList: [
            {
              bridgeId: null,
              menuDetailsId: null,
              menuItemId: null,
              menuItemName: ' ',
              mainMenuYn: 'Y',
              submenuDetails: null,
              submenuItem: null,
            },
            {
              bridgeId: null,
              menuDetailsId: null,
              menuItemId: null,
              menuItemName: ' ',
              mainMenuYn: 'N',
              submenuDetails: null,
              submenuItem: null,
            },
            {
              bridgeId: null,
              menuDetailsId: null,
              menuItemId: null,
              menuItemName: ' ',
              mainMenuYn: 'N',
              submenuDetails: null,
              submenuItem: null,
            },
            {
              bridgeId: null,
              menuDetailsId: null,
              menuItemId: null,
              menuItemName: ' ',
              mainMenuYn: 'N',
              submenuDetails: null,
              submenuItem: null,
            },
            {
              bridgeId: null,
              menuDetailsId: null,
              menuItemId: null,
              menuItemName: ' ',
              mainMenuYn: 'N',
              submenuDetails: null,
              submenuItem: null,
            },
          ],
        },
        {
          menuDetailsId: null,
          dailyMenuId: null,
          dailyMenuDate: null,
          dailyMenuCategory: null,
          mainMealYn: 'N',
          menuDetailsName: 'Plus',
          menuDetailsImgUrl: null,
          subBridgeList: [
            {
              bridgeId: null,
              menuDetailsId: null,
              menuItemId: null,
              menuItemName: ' ',
              mainMenuYn: 'N',
              submenuDetails: null,
              submenuItem: null,
            },
            {
              bridgeId: null,
              menuDetailsId: null,
              menuItemId: null,
              menuItemName: ' ',
              mainMenuYn: 'N',
              submenuDetails: null,
              submenuItem: null,
            },
          ],
        },
        {
          menuDetailsId: null,
          dailyMenuId: null,
          dailyMenuDate: null,
          dailyMenuCategory: null,
          mainMealYn: 'N',
          menuDetailsName: '',
          menuDetailsImgUrl: null,
          subBridgeList: [
            {
              bridgeId: null,
              menuDetailsId: null,
              menuItemId: null,
              menuItemName: ' ',
              mainMenuYn: 'N',
              submenuDetails: null,
              submenuItem: null,
            },
          ],
        },
        {
          menuDetailsId: null,
          dailyMenuId: null,
          dailyMenuDate: null,
          dailyMenuCategory: null,
          mainMealYn: 'Y',
          menuDetailsName: '석식',
          menuDetailsImgUrl: null,
          subBridgeList: [
            {
              bridgeId: null,
              menuDetailsId: null,
              menuItemId: null,
              menuItemName: ' ',
              mainMenuYn: 'Y',
              submenuDetails: null,
              submenuItem: null,
            },
            {
              bridgeId: null,
              menuDetailsId: null,
              menuItemId: null,
              menuItemName: ' ',
              mainMenuYn: 'N',
              submenuDetails: null,
              submenuItem: null,
            },
            {
              bridgeId: null,
              menuDetailsId: null,
              menuItemId: null,
              menuItemName: ' ',
              mainMenuYn: 'N',
              submenuDetails: null,
              submenuItem: null,
            },
            {
              bridgeId: null,
              menuDetailsId: null,
              menuItemId: null,
              menuItemName: ' ',
              mainMenuYn: 'N',
              submenuDetails: null,
              submenuItem: null,
            },
            {
              bridgeId: null,
              menuDetailsId: null,
              menuItemId: null,
              menuItemName: ' ',
              mainMenuYn: 'N',
              submenuDetails: null,
              submenuItem: null,
            },
          ],
        },
        {
          menuDetailsId: null,
          dailyMenuId: null,
          dailyMenuDate: null,
          dailyMenuCategory: null,
          mainMealYn: 'N',
          menuDetailsName: 'Plus',
          menuDetailsImgUrl: null,
          subBridgeList: [
            {
              bridgeId: null,
              menuDetailsId: null,
              menuItemId: null,
              menuItemName: ' ',
              mainMenuYn: 'N',
              submenuDetails: null,
              submenuItem: null,
            },
            {
              bridgeId: null,
              menuDetailsId: null,
              menuItemId: null,
              menuItemName: ' ',
              mainMenuYn: 'N',
              submenuDetails: null,
              submenuItem: null,
            },
          ],
        },
      ],
    },
    {
      dailyMenuId: null,
      menuDate: dayArr[1][2],
      holidayFg: 'N',
      restaurantOpenFg: 'Y',
      menuDetailsList: [
        {
          menuDetailsId: null,
          dailyMenuId: null,
          dailyMenuDate: null,
          dailyMenuCategory: null,
          mainMealYn: 'Y',
          menuDetailsName: '한식',
          menuDetailsImgUrl: null,
          subBridgeList: [
            {
              bridgeId: null,
              menuDetailsId: null,
              menuItemId: null,
              menuItemName: ' ',
              mainMenuYn: 'Y',
              submenuDetails: null,
              submenuItem: null,
            },
            {
              bridgeId: null,
              menuDetailsId: null,
              menuItemId: null,
              menuItemName: ' ',
              mainMenuYn: 'N',
              submenuDetails: null,
              submenuItem: null,
            },
            {
              bridgeId: null,
              menuDetailsId: null,
              menuItemId: null,
              menuItemName: ' ',
              mainMenuYn: 'N',
              submenuDetails: null,
              submenuItem: null,
            },
            {
              bridgeId: null,
              menuDetailsId: null,
              menuItemId: null,
              menuItemName: ' ',
              mainMenuYn: 'N',
              submenuDetails: null,
              submenuItem: null,
            },
            {
              bridgeId: null,
              menuDetailsId: null,
              menuItemId: null,
              menuItemName: ' ',
              mainMenuYn: 'N',
              submenuDetails: null,
              submenuItem: null,
            },
            {
              bridgeId: null,
              menuDetailsId: null,
              menuItemId: null,
              menuItemName: ' ',
              mainMenuYn: 'N',
              submenuDetails: null,
              submenuItem: null,
            },
          ],
        },
        {
          menuDetailsId: null,
          dailyMenuId: null,
          dailyMenuDate: null,
          dailyMenuCategory: null,
          mainMealYn: 'Y',
          menuDetailsName: '일품',
          menuDetailsImgUrl: null,
          subBridgeList: [
            {
              bridgeId: null,
              menuDetailsId: null,
              menuItemId: null,
              menuItemName: ' ',
              mainMenuYn: 'Y',
              submenuDetails: null,
              submenuItem: null,
            },
            {
              bridgeId: null,
              menuDetailsId: null,
              menuItemId: null,
              menuItemName: ' ',
              mainMenuYn: 'N',
              submenuDetails: null,
              submenuItem: null,
            },
            {
              bridgeId: null,
              menuDetailsId: null,
              menuItemId: null,
              menuItemName: ' ',
              mainMenuYn: 'N',
              submenuDetails: null,
              submenuItem: null,
            },
            {
              bridgeId: null,
              menuDetailsId: null,
              menuItemId: null,
              menuItemName: ' ',
              mainMenuYn: 'N',
              submenuDetails: null,
              submenuItem: null,
            },
            {
              bridgeId: null,
              menuDetailsId: null,
              menuItemId: null,
              menuItemName: ' ',
              mainMenuYn: 'N',
              submenuDetails: null,
              submenuItem: null,
            },
          ],
        },
        {
          menuDetailsId: null,
          dailyMenuId: null,
          dailyMenuDate: null,
          dailyMenuCategory: null,
          mainMealYn: 'N',
          menuDetailsName: 'Plus',
          menuDetailsImgUrl: null,
          subBridgeList: [
            {
              bridgeId: null,
              menuDetailsId: null,
              menuItemId: null,
              menuItemName: ' ',
              mainMenuYn: 'N',
              submenuDetails: null,
              submenuItem: null,
            },
            {
              bridgeId: null,
              menuDetailsId: null,
              menuItemId: null,
              menuItemName: ' ',
              mainMenuYn: 'N',
              submenuDetails: null,
              submenuItem: null,
            },
          ],
        },
        {
          menuDetailsId: null,
          dailyMenuId: null,
          dailyMenuDate: null,
          dailyMenuCategory: null,
          mainMealYn: 'N',
          menuDetailsName: '',
          menuDetailsImgUrl: null,
          subBridgeList: [
            {
              bridgeId: null,
              menuDetailsId: null,
              menuItemId: null,
              menuItemName: ' ',
              mainMenuYn: 'N',
              submenuDetails: null,
              submenuItem: null,
            },
          ],
        },
        {
          menuDetailsId: null,
          dailyMenuId: null,
          dailyMenuDate: null,
          dailyMenuCategory: null,
          mainMealYn: 'Y',
          menuDetailsName: '석식',
          menuDetailsImgUrl: null,
          subBridgeList: [
            {
              bridgeId: null,
              menuDetailsId: null,
              menuItemId: null,
              menuItemName: ' ',
              mainMenuYn: 'Y',
              submenuDetails: null,
              submenuItem: null,
            },
            {
              bridgeId: null,
              menuDetailsId: null,
              menuItemId: null,
              menuItemName: ' ',
              mainMenuYn: 'N',
              submenuDetails: null,
              submenuItem: null,
            },
            {
              bridgeId: null,
              menuDetailsId: null,
              menuItemId: null,
              menuItemName: ' ',
              mainMenuYn: 'N',
              submenuDetails: null,
              submenuItem: null,
            },
            {
              bridgeId: null,
              menuDetailsId: null,
              menuItemId: null,
              menuItemName: ' ',
              mainMenuYn: 'N',
              submenuDetails: null,
              submenuItem: null,
            },
            {
              bridgeId: null,
              menuDetailsId: null,
              menuItemId: null,
              menuItemName: ' ',
              mainMenuYn: 'N',
              submenuDetails: null,
              submenuItem: null,
            },
          ],
        },
        {
          menuDetailsId: null,
          dailyMenuId: null,
          dailyMenuDate: null,
          dailyMenuCategory: null,
          mainMealYn: 'N',
          menuDetailsName: 'Plus',
          menuDetailsImgUrl: null,
          subBridgeList: [
            {
              bridgeId: null,
              menuDetailsId: null,
              menuItemId: null,
              menuItemName: ' ',
              mainMenuYn: 'N',
              submenuDetails: null,
              submenuItem: null,
            },
            {
              bridgeId: null,
              menuDetailsId: null,
              menuItemId: null,
              menuItemName: ' ',
              mainMenuYn: 'N',
              submenuDetails: null,
              submenuItem: null,
            },
          ],
        },
      ],
    },
    {
      dailyMenuId: null,
      menuDate: dayArr[2][2],
      holidayFg: 'N',
      restaurantOpenFg: 'Y',
      menuDetailsList: [
        {
          menuDetailsId: null,
          dailyMenuId: null,
          dailyMenuDate: null,
          dailyMenuCategory: null,
          mainMealYn: 'Y',
          menuDetailsName: '한식',
          menuDetailsImgUrl: null,
          subBridgeList: [
            {
              bridgeId: null,
              menuDetailsId: null,
              menuItemId: null,
              menuItemName: ' ',
              mainMenuYn: 'Y',
              submenuDetails: null,
              submenuItem: null,
            },
            {
              bridgeId: null,
              menuDetailsId: null,
              menuItemId: null,
              menuItemName: ' ',
              mainMenuYn: 'N',
              submenuDetails: null,
              submenuItem: null,
            },
            {
              bridgeId: null,
              menuDetailsId: null,
              menuItemId: null,
              menuItemName: ' ',
              mainMenuYn: 'N',
              submenuDetails: null,
              submenuItem: null,
            },
            {
              bridgeId: null,
              menuDetailsId: null,
              menuItemId: null,
              menuItemName: ' ',
              mainMenuYn: 'N',
              submenuDetails: null,
              submenuItem: null,
            },
            {
              bridgeId: null,
              menuDetailsId: null,
              menuItemId: null,
              menuItemName: ' ',
              mainMenuYn: 'N',
              submenuDetails: null,
              submenuItem: null,
            },
            {
              bridgeId: null,
              menuDetailsId: null,
              menuItemId: null,
              menuItemName: ' ',
              mainMenuYn: 'N',
              submenuDetails: null,
              submenuItem: null,
            },
          ],
        },
        {
          menuDetailsId: null,
          dailyMenuId: null,
          dailyMenuDate: null,
          dailyMenuCategory: null,
          mainMealYn: 'Y',
          menuDetailsName: '일품',
          menuDetailsImgUrl: null,
          subBridgeList: [
            {
              bridgeId: null,
              menuDetailsId: null,
              menuItemId: null,
              menuItemName: ' ',
              mainMenuYn: 'Y',
              submenuDetails: null,
              submenuItem: null,
            },
            {
              bridgeId: null,
              menuDetailsId: null,
              menuItemId: null,
              menuItemName: ' ',
              mainMenuYn: 'N',
              submenuDetails: null,
              submenuItem: null,
            },
            {
              bridgeId: null,
              menuDetailsId: null,
              menuItemId: null,
              menuItemName: ' ',
              mainMenuYn: 'N',
              submenuDetails: null,
              submenuItem: null,
            },
            {
              bridgeId: null,
              menuDetailsId: null,
              menuItemId: null,
              menuItemName: ' ',
              mainMenuYn: 'N',
              submenuDetails: null,
              submenuItem: null,
            },
            {
              bridgeId: null,
              menuDetailsId: null,
              menuItemId: null,
              menuItemName: ' ',
              mainMenuYn: 'N',
              submenuDetails: null,
              submenuItem: null,
            },
          ],
        },
        {
          menuDetailsId: null,
          dailyMenuId: null,
          dailyMenuDate: null,
          dailyMenuCategory: null,
          mainMealYn: 'N',
          menuDetailsName: 'Plus',
          menuDetailsImgUrl: null,
          subBridgeList: [
            {
              bridgeId: null,
              menuDetailsId: null,
              menuItemId: null,
              menuItemName: ' ',
              mainMenuYn: 'N',
              submenuDetails: null,
              submenuItem: null,
            },
            {
              bridgeId: null,
              menuDetailsId: null,
              menuItemId: null,
              menuItemName: ' ',
              mainMenuYn: 'N',
              submenuDetails: null,
              submenuItem: null,
            },
          ],
        },
        {
          menuDetailsId: null,
          dailyMenuId: null,
          dailyMenuDate: null,
          dailyMenuCategory: null,
          mainMealYn: 'N',
          menuDetailsName: '샐러드팩',
          menuDetailsImgUrl: null,
          subBridgeList: [
            {
              bridgeId: null,
              menuDetailsId: null,
              menuItemId: null,
              menuItemName: ' ',
              mainMenuYn: 'N',
              submenuDetails: null,
              submenuItem: null,
            },
          ],
        },
        {
          menuDetailsId: null,
          dailyMenuId: null,
          dailyMenuDate: null,
          dailyMenuCategory: null,
          mainMealYn: 'Y',
          menuDetailsName: '석식',
          menuDetailsImgUrl: null,
          subBridgeList: [
            {
              bridgeId: null,
              menuDetailsId: null,
              menuItemId: null,
              menuItemName: ' ',
              mainMenuYn: 'Y',
              submenuDetails: null,
              submenuItem: null,
            },
            {
              bridgeId: null,
              menuDetailsId: null,
              menuItemId: null,
              menuItemName: ' ',
              mainMenuYn: 'N',
              submenuDetails: null,
              submenuItem: null,
            },
            {
              bridgeId: null,
              menuDetailsId: null,
              menuItemId: null,
              menuItemName: ' ',
              mainMenuYn: 'N',
              submenuDetails: null,
              submenuItem: null,
            },
            {
              bridgeId: null,
              menuDetailsId: null,
              menuItemId: null,
              menuItemName: ' ',
              mainMenuYn: 'N',
              submenuDetails: null,
              submenuItem: null,
            },
            {
              bridgeId: null,
              menuDetailsId: null,
              menuItemId: null,
              menuItemName: ' ',
              mainMenuYn: 'N',
              submenuDetails: null,
              submenuItem: null,
            },
          ],
        },
        {
          menuDetailsId: null,
          dailyMenuId: null,
          dailyMenuDate: null,
          dailyMenuCategory: null,
          mainMealYn: 'N',
          menuDetailsName: 'Plus',
          menuDetailsImgUrl: null,
          subBridgeList: [
            {
              bridgeId: null,
              menuDetailsId: null,
              menuItemId: null,
              menuItemName: ' ',
              mainMenuYn: 'N',
              submenuDetails: null,
              submenuItem: null,
            },
            {
              bridgeId: null,
              menuDetailsId: null,
              menuItemId: null,
              menuItemName: ' ',
              mainMenuYn: 'N',
              submenuDetails: null,
              submenuItem: null,
            },
          ],
        },
      ],
    },
    {
      dailyMenuId: null,
      menuDate: dayArr[3][2],
      holidayFg: 'N',
      restaurantOpenFg: 'Y',
      menuDetailsList: [
        {
          menuDetailsId: null,
          dailyMenuId: null,
          dailyMenuDate: null,
          dailyMenuCategory: null,
          mainMealYn: 'Y',
          menuDetailsName: '한식',
          menuDetailsImgUrl: null,
          subBridgeList: [
            {
              bridgeId: null,
              menuDetailsId: null,
              menuItemId: null,
              menuItemName: ' ',
              mainMenuYn: 'Y',
              submenuDetails: null,
              submenuItem: null,
            },
            {
              bridgeId: null,
              menuDetailsId: null,
              menuItemId: null,
              menuItemName: ' ',
              mainMenuYn: 'N',
              submenuDetails: null,
              submenuItem: null,
            },
            {
              bridgeId: null,
              menuDetailsId: null,
              menuItemId: null,
              menuItemName: ' ',
              mainMenuYn: 'N',
              submenuDetails: null,
              submenuItem: null,
            },
            {
              bridgeId: null,
              menuDetailsId: null,
              menuItemId: null,
              menuItemName: ' ',
              mainMenuYn: 'N',
              submenuDetails: null,
              submenuItem: null,
            },
            {
              bridgeId: null,
              menuDetailsId: null,
              menuItemId: null,
              menuItemName: ' ',
              mainMenuYn: 'N',
              submenuDetails: null,
              submenuItem: null,
            },
            {
              bridgeId: null,
              menuDetailsId: null,
              menuItemId: null,
              menuItemName: ' ',
              mainMenuYn: 'N',
              submenuDetails: null,
              submenuItem: null,
            },
          ],
        },
        {
          menuDetailsId: null,
          dailyMenuId: null,
          dailyMenuDate: null,
          dailyMenuCategory: null,
          mainMealYn: 'Y',
          menuDetailsName: '일품',
          menuDetailsImgUrl: null,
          subBridgeList: [
            {
              bridgeId: null,
              menuDetailsId: null,
              menuItemId: null,
              menuItemName: ' ',
              mainMenuYn: 'Y',
              submenuDetails: null,
              submenuItem: null,
            },
            {
              bridgeId: null,
              menuDetailsId: null,
              menuItemId: null,
              menuItemName: ' ',
              mainMenuYn: 'N',
              submenuDetails: null,
              submenuItem: null,
            },
            {
              bridgeId: null,
              menuDetailsId: null,
              menuItemId: null,
              menuItemName: ' ',
              mainMenuYn: 'N',
              submenuDetails: null,
              submenuItem: null,
            },
            {
              bridgeId: null,
              menuDetailsId: null,
              menuItemId: null,
              menuItemName: ' ',
              mainMenuYn: 'N',
              submenuDetails: null,
              submenuItem: null,
            },
            {
              bridgeId: null,
              menuDetailsId: null,
              menuItemId: null,
              menuItemName: ' ',
              mainMenuYn: 'N',
              submenuDetails: null,
              submenuItem: null,
            },
          ],
        },
        {
          menuDetailsId: null,
          dailyMenuId: null,
          dailyMenuDate: null,
          dailyMenuCategory: null,
          mainMealYn: 'N',
          menuDetailsName: 'Plus',
          menuDetailsImgUrl: null,
          subBridgeList: [
            {
              bridgeId: null,
              menuDetailsId: null,
              menuItemId: null,
              menuItemName: ' ',
              mainMenuYn: 'N',
              submenuDetails: null,
              submenuItem: null,
            },
            {
              bridgeId: null,
              menuDetailsId: null,
              menuItemId: null,
              menuItemName: ' ',
              mainMenuYn: 'N',
              submenuDetails: null,
              submenuItem: null,
            },
          ],
        },
        {
          menuDetailsId: null,
          dailyMenuId: null,
          dailyMenuDate: null,
          dailyMenuCategory: null,
          mainMealYn: 'N',
          menuDetailsName: '샐러드팩',
          menuDetailsImgUrl: null,
          subBridgeList: [
            {
              bridgeId: null,
              menuDetailsId: null,
              menuItemId: null,
              menuItemName: ' ',
              mainMenuYn: 'N',
              submenuDetails: null,
              submenuItem: null,
            },
          ],
        },
        {
          menuDetailsId: null,
          dailyMenuId: null,
          dailyMenuDate: null,
          dailyMenuCategory: null,
          mainMealYn: 'Y',
          menuDetailsName: '석식',
          menuDetailsImgUrl: null,
          subBridgeList: [
            {
              bridgeId: null,
              menuDetailsId: null,
              menuItemId: null,
              menuItemName: ' ',
              mainMenuYn: 'Y',
              submenuDetails: null,
              submenuItem: null,
            },
            {
              bridgeId: null,
              menuDetailsId: null,
              menuItemId: null,
              menuItemName: ' ',
              mainMenuYn: 'N',
              submenuDetails: null,
              submenuItem: null,
            },
            {
              bridgeId: null,
              menuDetailsId: null,
              menuItemId: null,
              menuItemName: ' ',
              mainMenuYn: 'N',
              submenuDetails: null,
              submenuItem: null,
            },
            {
              bridgeId: null,
              menuDetailsId: null,
              menuItemId: null,
              menuItemName: ' ',
              mainMenuYn: 'N',
              submenuDetails: null,
              submenuItem: null,
            },
            {
              bridgeId: null,
              menuDetailsId: null,
              menuItemId: null,
              menuItemName: ' ',
              mainMenuYn: 'N',
              submenuDetails: null,
              submenuItem: null,
            },
          ],
        },
        {
          menuDetailsId: null,
          dailyMenuId: null,
          dailyMenuDate: null,
          dailyMenuCategory: null,
          mainMealYn: 'N',
          menuDetailsName: 'Plus',
          menuDetailsImgUrl: null,
          subBridgeList: [
            {
              bridgeId: null,
              menuDetailsId: null,
              menuItemId: null,
              menuItemName: ' ',
              mainMenuYn: 'N',
              submenuDetails: null,
              submenuItem: null,
            },
            {
              bridgeId: null,
              menuDetailsId: null,
              menuItemId: null,
              menuItemName: ' ',
              mainMenuYn: 'N',
              submenuDetails: null,
              submenuItem: null,
            },
          ],
        },
      ],
    },
    {
      dailyMenuId: null,
      menuDate: dayArr[4][2],
      holidayFg: 'N',
      restaurantOpenFg: 'Y',
      menuDetailsList: [
        {
          menuDetailsId: null,
          dailyMenuId: null,
          dailyMenuDate: null,
          dailyMenuCategory: null,
          mainMealYn: 'Y',
          menuDetailsName: '한식',
          menuDetailsImgUrl: null,
          subBridgeList: [
            {
              bridgeId: null,
              menuDetailsId: null,
              menuItemId: null,
              menuItemName: ' ',
              mainMenuYn: 'Y',
              submenuDetails: null,
              submenuItem: null,
            },
            {
              bridgeId: null,
              menuDetailsId: null,
              menuItemId: null,
              menuItemName: ' ',
              mainMenuYn: 'N',
              submenuDetails: null,
              submenuItem: null,
            },
            {
              bridgeId: null,
              menuDetailsId: null,
              menuItemId: null,
              menuItemName: ' ',
              mainMenuYn: 'N',
              submenuDetails: null,
              submenuItem: null,
            },
            {
              bridgeId: null,
              menuDetailsId: null,
              menuItemId: null,
              menuItemName: ' ',
              mainMenuYn: 'N',
              submenuDetails: null,
              submenuItem: null,
            },
            {
              bridgeId: null,
              menuDetailsId: null,
              menuItemId: null,
              menuItemName: ' ',
              mainMenuYn: 'N',
              submenuDetails: null,
              submenuItem: null,
            },
            {
              bridgeId: null,
              menuDetailsId: null,
              menuItemId: null,
              menuItemName: ' ',
              mainMenuYn: 'N',
              submenuDetails: null,
              submenuItem: null,
            },
          ],
        },
        {
          menuDetailsId: null,
          dailyMenuId: null,
          dailyMenuDate: null,
          dailyMenuCategory: null,
          mainMealYn: 'Y',
          menuDetailsName: '일품',
          menuDetailsImgUrl: null,
          subBridgeList: [
            {
              bridgeId: null,
              menuDetailsId: null,
              menuItemId: null,
              menuItemName: ' ',
              mainMenuYn: 'Y',
              submenuDetails: null,
              submenuItem: null,
            },
            {
              bridgeId: null,
              menuDetailsId: null,
              menuItemId: null,
              menuItemName: ' ',
              mainMenuYn: 'N',
              submenuDetails: null,
              submenuItem: null,
            },
            {
              bridgeId: null,
              menuDetailsId: null,
              menuItemId: null,
              menuItemName: ' ',
              mainMenuYn: 'N',
              submenuDetails: null,
              submenuItem: null,
            },
            {
              bridgeId: null,
              menuDetailsId: null,
              menuItemId: null,
              menuItemName: ' ',
              mainMenuYn: 'N',
              submenuDetails: null,
              submenuItem: null,
            },
            {
              bridgeId: null,
              menuDetailsId: null,
              menuItemId: null,
              menuItemName: ' ',
              mainMenuYn: 'N',
              submenuDetails: null,
              submenuItem: null,
            },
          ],
        },
        {
          menuDetailsId: null,
          dailyMenuId: null,
          dailyMenuDate: null,
          dailyMenuCategory: null,
          mainMealYn: 'N',
          menuDetailsName: 'Plus',
          menuDetailsImgUrl: null,
          subBridgeList: [
            {
              bridgeId: null,
              menuDetailsId: null,
              menuItemId: null,
              menuItemName: ' ',
              mainMenuYn: 'N',
              submenuDetails: null,
              submenuItem: null,
            },
            {
              bridgeId: null,
              menuDetailsId: null,
              menuItemId: null,
              menuItemName: ' ',
              mainMenuYn: 'N',
              submenuDetails: null,
              submenuItem: null,
            },
          ],
        },
        {
          menuDetailsId: null,
          dailyMenuId: null,
          dailyMenuDate: null,
          dailyMenuCategory: null,
          mainMealYn: 'N',
          menuDetailsName: '샐러드팩',
          menuDetailsImgUrl: null,
          subBridgeList: [
            {
              bridgeId: null,
              menuDetailsId: null,
              menuItemId: null,
              menuItemName: ' ',
              mainMenuYn: 'N',
              submenuDetails: null,
              submenuItem: null,
            },
          ],
        },
        {
          menuDetailsId: null,
          dailyMenuId: null,
          dailyMenuDate: null,
          dailyMenuCategory: null,
          mainMealYn: 'Y',
          menuDetailsName: '석식',
          menuDetailsImgUrl: null,
          subBridgeList: [
            {
              bridgeId: null,
              menuDetailsId: null,
              menuItemId: null,
              menuItemName: ' ',
              mainMenuYn: 'Y',
              submenuDetails: null,
              submenuItem: null,
            },
            {
              bridgeId: null,
              menuDetailsId: null,
              menuItemId: null,
              menuItemName: ' ',
              mainMenuYn: 'N',
              submenuDetails: null,
              submenuItem: null,
            },
            {
              bridgeId: null,
              menuDetailsId: null,
              menuItemId: null,
              menuItemName: ' ',
              mainMenuYn: 'N',
              submenuDetails: null,
              submenuItem: null,
            },
            {
              bridgeId: null,
              menuDetailsId: null,
              menuItemId: null,
              menuItemName: ' ',
              mainMenuYn: 'N',
              submenuDetails: null,
              submenuItem: null,
            },
            {
              bridgeId: null,
              menuDetailsId: null,
              menuItemId: null,
              menuItemName: ' ',
              mainMenuYn: 'N',
              submenuDetails: null,
              submenuItem: null,
            },
          ],
        },
        {
          menuDetailsId: null,
          dailyMenuId: null,
          dailyMenuDate: null,
          dailyMenuCategory: null,
          mainMealYn: 'N',
          menuDetailsName: 'Plus',
          menuDetailsImgUrl: null,
          subBridgeList: [
            {
              bridgeId: null,
              menuDetailsId: null,
              menuItemId: null,
              menuItemName: ' ',
              mainMenuYn: 'N',
              submenuDetails: null,
              submenuItem: null,
            },
            {
              bridgeId: null,
              menuDetailsId: null,
              menuItemId: null,
              menuItemName: ' ',
              mainMenuYn: 'N',
              submenuDetails: null,
              submenuItem: null,
            },
          ],
        },
      ],
    },
  ];
};
